### ISSUE TITLE
Adapt your Flutter app to Android 13 - Permission.photos

### ISSUE THREAD

**Issue by robsonamendonca** [Nialixus/filesaverz#4]
//Android 13 or high
  Permission photos = Permission.photos;
  await photos.request();
  PermissionStatus permissionStatusPhotos = await photos.status;

**Comment by Nialixus** [comment]
Hi, I'm wondering what would happen if we use Permission.manageExternalStorage instead of just Permission.photos?

By the way, I've updated the package on pub.dev.

**Comment by robsonamendonca** [comment]
The android.permission.MANAGE_EXTERNAL_STORAGE permission is introduced with Android 11 (API 30) and therefore not supported on Android 10 or lower (see official documentation).

The permission_handler plugin returns PermissionStatus.restricted because it doesn't know how to handle the permission on Android 10 and below. In case of Android 10 and lower simply restrict to requesting the android.permission.READ_EXTERNAL_STORAGE and android.permission.WRITE_EXTERNAL_STORAGE permissions.

The log message is printed because the android.permission.MANAGE_EXTERNAL_STORAGE permission is not returned as part of the array returned by the Context.getPackageInfo().requestedPermissions API. Therefore the permission_handler plugin thinks the permission is not listed in the AndroidManifest.xml file. In this case this is of course not entirely true, however my assumption is that Android filters out permissions that don't apply on the current Android version.

As maintainer of the permission_handler plugin I will make sure the log message gets updated so it takes this option also into account.

Fontes: https://stackoverflow.com/questions/69759723/restricted-access-to-external-storage-android-10

**Comment by Nialixus** [comment]
Alright, let me know if the filesaver v3.1.0 working just fine, so that i can close this
